#!/bin/bash
# Re-creates vendor/trystero and vendor/noble-secp256k1 from their upstream git tags.
#
# DuetBox vendors these instead of installing them from npm so the existing
# `npm ci` / package-lock.json workflow stays untouched. The sources are
# compiled by the regular `npx tsc` step together with the editor, which needs
# a few mechanical adjustments that this script applies:
#   - package imports are rewritten to relative paths,
#   - Trystero's `DEV:` debug logging (stripped by its own bundler) is disabled,
#   - a handshake field starting with "__" is renamed so the minifier leaves it alone,
#   - files that don't pass this project's stricter / ES6-targeted type checks
#     get `// @ts-nocheck`, and the one BigInt `**` (which TypeScript would
#     down-level to Math.pow when targeting ES6) is rewritten as a shift.
set -e

TRYSTERO_TAG="0.26.0"
NOBLE_TAG="3.2.0"

cd "$(dirname "$0")/.."
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

git -c advice.detachedHead=false clone --quiet --depth 1 --branch "$TRYSTERO_TAG" https://github.com/dmotz/trystero "$tmp/trystero"
git -c advice.detachedHead=false clone --quiet --depth 1 --branch "$NOBLE_TAG" https://github.com/paulmillr/noble-secp256k1 "$tmp/noble"

rm -rf vendor/trystero vendor/noble-secp256k1
mkdir -p vendor/trystero/core vendor/noble-secp256k1

cp "$tmp"/trystero/packages/core/src/*.ts vendor/trystero/core/
cp "$tmp/trystero/packages/nostr/src/index.ts" vendor/trystero/nostr.ts
cp "$tmp/trystero/LICENSE" vendor/trystero/LICENSE
cp "$tmp/noble/index.ts" vendor/noble-secp256k1/index.ts
cp "$tmp/noble/LICENSE" vendor/noble-secp256k1/LICENSE

perl -pi -e "s#from '\@noble/secp256k1'#from '../noble-secp256k1/index'#; s#from '\@trystero-p2p/core'#from './core/index'#" vendor/trystero/nostr.ts
perl -pi -e 's/\bDEV: log\(/DEV: false && log(/' vendor/trystero/core/*.ts vendor/trystero/nostr.ts
perl -pi -e 's/2n \*\* 256n/(1n << 256n)/' vendor/noble-secp256k1/index.ts
# The editor's minifier renames every property that starts with "_", which would make this
# handshake field differ between builds (e.g. minified vs. debug) and stop them connecting.
perl -pi -e 's/__trystero_pw/trystero_pw/g' vendor/trystero/core/handshake.ts

for file in vendor/noble-secp256k1/index.ts vendor/trystero/core/peer.ts vendor/trystero/core/signal-handler.ts; do
	perl -0pi -e 's/^/\/\/ \@ts-nocheck -- vendored source, see scripts\/vendor_trystero.sh\n/' "$file"
done

cat > vendor/README.md <<EOF
# Vendored dependencies

These directories are generated by \`scripts/vendor_trystero.sh\`; edit that script instead of the files.

- \`trystero/\`: [Trystero](https://github.com/dmotz/trystero) $TRYSTERO_TAG (core + Nostr strategy), MIT license.
- \`noble-secp256k1/\`: [noble-secp256k1](https://github.com/paulmillr/noble-secp256k1) $NOBLE_TAG, MIT license.
EOF

echo "Vendored trystero $TRYSTERO_TAG and noble-secp256k1 $NOBLE_TAG."
